src/expensereport/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(pattern_name='expenses:dashboard',
                                    permanent=False)),
    url(r'^expense/', include('expenses.urls', namespace='expenses')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        name="logout"),


    # Examples:
    # url(r'^$', 'expensereport.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/expenses/urls.py
from django.conf.urls import url, patterns, include

from rest_framework import routers

from .views import ExpenseViewSet

router = routers.SimpleRouter()
router.register(r'', ExpenseViewSet)


urlpatterns = patterns('expenses.views',
    url(r'^$', 'dashboard', name='dashboard'),
    url(r'^summary/$', 'summary', name='summary'),
    url(r'^attendee/(?P<username>[\w_@+.-]+)-receipts.zip$', 'receipts',
        name='receipts'),
    url(r'^attendee/(?P<username>[\w_@+.-]+)/$', 'dashboard', name='attendee'),
)

urlpatterns += patterns('',
    url(r'^api', include(router.urls)),
)

src/expenses/models.py
import os

from django.db import models
from django.utils.text import slugify

from django.contrib.auth.models import User
from django.utils.translation import ugettext as _


def update_to(instance, filename):
    filename, extension = os.path.splitext(filename) 
    user_slug = slugify(instance.attendee.get_full_name())

    filename = '_'.join([unicode(instance.date), user_slug, instance.category])
    return os.path.join(user_slug, filename) + extension


class Expense(models.Model):
    CATEGORY_CHOICES = (
        ('transport-local', _('Local Transportation (Metro/Bus/Taxi)')),
        ('food', _('Food')),
        ('swag', _('Swag')),
        ('hotel', _('Hotel')),
        ('credentials', _('Event Credentials')),
        ('transport-long', _('Long Transportation (Flight/Train/Bus)')),
    )

    date = models.DateField()
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    # currency = ...
    description = models.CharField(max_length=255)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=80)
    receipt = models.ImageField(upload_to=update_to)

    attendee = models.ForeignKey(User)

    class Meta:
        ordering = ["attendee__first_name", "date"]


    def __unicode__(self):
        amount_formatted = u"{0:.2f}".format(self.amount)
        return u'{} spent R${} on {} in {} ({})'.format(
            self.attendee.get_full_name(),
            amount_formatted,
            self.date,
            self.get_category_display(),
            self.description,
        )


class PaypalAccount(models.Model):
    user = models.ForeignKey(User, unique=True)
    paypal_account = models.EmailField()

    def __unicode__(self):
        return u"{} ({})".format(self.paypal_account, self.user.get_full_name())

src/expenses/views.py
# *-* coding: utf-8 *-*

import os
import zipfile
import tempfile

from decimal import Decimal
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.db.models import Sum
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.conf import settings

from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from .models import Expense
from .serializers import ExpenseSerializer


class ExpenseViewSet(viewsets.ModelViewSet):
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer
    permission_classes = (IsAuthenticated,)


@login_required
def dashboard(request, username=None):
    if username:
        user = get_object_or_404(User, username=username)
        qs = Expense.objects.filter(attendee_id=user.id)
    else:
        user = None
        qs = Expense.objects

    n_attendees = User.objects.count()
    total_amount = qs.aggregate(Sum('amount'))

    expenses = []
    for expense in qs.all():
        user_link = reverse('expenses:attendee', kwargs={
            'username': expense.attendee.username,
        })
        user_name = expense.attendee.first_name

        expenses.append((
            u'<a href="{}">{}</a>'.format(user_link, user_name),
            expense.amount,
            expense.date,
            expense.get_category_display(),
            expense.description,
            u'<a href="{}">link</a>'.format(expense.receipt.url),
        ))

    by_category = qs.values('category').annotate(Sum('amount')).order_by()
    by_attendee = qs.values('attendee__first_name').\
                                        annotate(Sum('amount')).order_by()
    context = {
        'headers': (
            'Name',
            'Amount (R$)',
            'Date',
            'Category',
            'Description',
            'Receipt',
        ),
        'data': expenses,
        'n_attendees': n_attendees,
        'attendee': user,
        'expense_by_category': by_category,
        'expense_by_attendee': by_attendee,
        'total_amount': total_amount['amount__sum'],
    }

    return render(request, 'dashboard.html', context)

@login_required
def summary(request):

    qs = Expense.objects.values('attendee__first_name')
    qs = qs.annotate(Sum('amount')).order_by()
    qs = qs.values(
        'attendee__paypalaccount__paypal_account',
        'amount__sum',
        'attendee__first_name',
        'attendee__username',
    )

    expenses = []
    for expense in qs:
        user_link = reverse('expenses:attendee', kwargs={
            'username': expense['attendee__username'],
        })
        zip_link = reverse('expenses:receipts', kwargs={
            'username': expense['attendee__username'],
        })

        user_name = expense['attendee__first_name']
        amount_usd = (expense['amount__sum'] /
                      settings.BRL_USD_RATE *
                      settings.PAYPAL_RATE).quantize(Decimal('1.00'))
        expenses.append((
            u'<a href="{}">{}</a>'.format(user_link, user_name),
            expense['attendee__paypalaccount__paypal_account'],
            expense['amount__sum'],
            amount_usd,
            u'<a href="{}">link</a>'.format(zip_link),
        ))
    n_attendees = User.objects.count()
    total_amount = Expense.objects.aggregate(Sum('amount'))

    context = {
        'headers': (
            'Name',
            'Paypal',
            'Amount (BRL)',
            'Amount (USD)',
            'Receipts (.zip)',
        ),
        'data': expenses,
        'n_attendees': n_attendees,
        'total_amount': total_amount['amount__sum'],
    }
    return render(request, 'summary.html', context)


@login_required
def receipts(request, username=None):

    # Get user
    user = get_object_or_404(User, username=username)

    # Check if the user has expenses
    expenses = Expense.objects.filter(attendee_id=user.id)
    if not expenses:
        raise Http404('No Expenses for user {}'.format(user.username))

    # Create zips folder on MEDIA_ROOT
    zips_path = os.path.join(settings.MEDIA_ROOT, 'zips')
    if not os.path.exists(zips_path):
        os.mkdir(zips_path)

    # Gets the file path for the zip that will be created now
    filename = '-'.join([username, 'receipts.zip'])
    file_path = os.path.join(zips_path, filename)

    # Create the zip
    zf = zipfile.ZipFile(file_path, "w", zipfile.ZIP_DEFLATED)
    for expense in expenses:
        zf.write(expense.receipt.path, expense.receipt.name)
    zf.close()

    # Redirect to the place where the zip will be hosted
    return redirect(settings.MEDIA_URL + 'zips/' + filename)

src/expenses/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <!-- Title and other stuffs -->
  <title>{% block title %}Mozilla Reps - Expense Report{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- TODO -->
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">
  <!-- END TODO -->

  <!-- Stylesheets -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Font awesome icon -->
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
  <!-- jQuery UI -->
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" type="text/css">
  <!-- Calendar -->
  <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}" type="text/css">
  <!-- prettyPhoto -->
  <link rel="stylesheet" href="{% static 'css/prettyPhoto.css' %}" type="text/css">
  <!-- Star rating -->
  <link rel="stylesheet" href="{% static 'css/rateit.css' %}" type="text/css">
  <!-- Date picker -->
  <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}" type="text/css">
  <!-- CLEditor -->
  <link rel="stylesheet" href="{% static 'css/jquery.cleditor.css' %}" type="text/css">
  <!-- Data tables -->
  <link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}" type="text/css">
  <!-- Bootstrap toggle -->
  <link rel="stylesheet" href="{% static 'css/jquery.onoff.css' %}" type="text/css">
  <!-- Main stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  <!-- Widgets stylesheet -->
  <link href="{% static 'css/widgets.css' %}" rel="stylesheet" type="text/css">


  <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css">

  <script src="{% static 'js/respond.min.js' %}"></script>
  <!--[if lt IE 9]>
  <script src="{% static 'js/html5shiv.js' %}"></script>
  <![endif]-->

  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static 'img/remo/shortcut.ico' %}">
</head>

<body>
{% block body %}

<div class="navbar navbar-fixed-top bs-docs-nav" role="banner">

    <div class="conjtainer">
      <!-- Menu button for smallar screens -->
      <div class="navbar-header">
		  <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			<span>Menu</span>
		  </button>
		  <!-- Site name for smallar screens -->
		  <a href="{% url 'expenses:dashboard' %}" class="navbar-brand hidden-lg">
            <img src="{% static 'img/remo/remo_logo_medium.png' %}" alt="Mozilla Reps logo">
            ExpenseReport
          </a>
		</div>



      <!-- Navigation starts -->
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <!-- Links -->
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown pull-right">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
              <i class="fa fa-user"></i> {% firstof user.first_name user.username %} <b class="caret"></b>
            </a>

            <!-- Dropdown menu -->
            <ul class="dropdown-menu">
              {% comment %}
              <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
              <li><a href="#"><i class="fa fa-cogs"></i> Settings</a></li>
              {% endcomment %}
              <li><a href="{% url 'logout' %}?next={% url 'expenses:dashboard' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
            </ul>
          </li>

        </ul>
      </nav>

    </div>
  </div>


<!-- Header starts -->
  <header>
    <div class="container">
      <div class="row">

        <!-- Logo section -->
        <div class="col-md-4">
          <!-- Logo. -->
          <div class="logo">
            <h1>
                <img src="{% static 'img/remo/remo_logo_medium.png' %}" alt="Mozilla Reps Logo" />
                <a href="#">Expense<span class="bold">Report</span></a>
            </h1>
            <p class="meta">Mozilla Reps</p>
          </div>
          <!-- Logo ends -->
        </div>

        <!-- Button section -->
        <div class="col-md-4">
        </div>

        <!-- Data section -->

        <div class="col-md-4">
          <div class="header-data pull-right">

            {% comment %}
            <!-- Traffic data -->
            <div class="hdata">
              <div class="mcol-left">
                <!-- Icon with red background -->
                <i class="fa fa-signal bred"></i>
              </div>
              <div class="mcol-right">
                <!-- Number of visitors -->
                <p><a href="#">7000</a> <em>visits</em></p>
              </div>
              <div class="clearfix"></div>
            </div>
            {% endcomment %}

            {% if not attendee %}
            <!-- Members data -->
            <div class="hdata">
              <div class="mcol-left">
                <!-- Icon with blue background -->
                <i class="fa fa-user bblue"></i>
              </div>
              <div class="mcol-right">
                <!-- Number of visitors -->
                <p>{{ n_attendees }}<em>attendees</em></p>
              </div>
              <div class="clearfix"></div>
            </div>
            {% endif %}

            <!-- revenue data -->
            <div class="hdata">
              <div class="mcol-left">
                <!-- Icon with green background -->
                <i class="fa fa-money bgreen"></i>
              </div>
              <div class="mcol-right">
                <!-- Number of visitors -->
                <p>R$ {{ total_amount }}<em>spent</em></p>
              </div>
              <div class="clearfix"></div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </header>

<!-- Header ends -->

<!-- Content starts -->
{% block content %}
<div class="content">

  <!-- Sidebar -->
  <div class="sidebar">
    <div class="sidebar-dropdown"><a href="#">Navigation</a></div>

    <!--- Sidebar navigation -->
    <!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
    <ul id="nav">
      <!-- Main menu with font awesome icon -->
      <li><a href="{% url 'expenses:dashboard' %}"><i class="fa fa-home"></i> Dashboard</a>
        <!-- Sub menu markup
        <ul>
          <li><a href="#">Submenu #1</a></li>
          <li><a href="#">Submenu #2</a></li>
          <li><a href="#">Submenu #3</a></li>
        </ul>-->

      </li>
      <li><a href="{% url 'expenses:summary' %}"><i class="fa fa-table"></i> Summary</a></li>
    </ul>
  </div>
  <!-- Sidebar ends -->

  <!-- Main bar -->
  <div class="mainbar">

    <!-- Page heading -->
    <div class="page-head">
      <h2 class="pull-left"><i class="fa fa-home"></i> {% block page-title %}FISL 15{% endblock %}</h2>

      <!-- Breadcrumb -->
      <div class="bread-crumb pull-right">
        <a href="index.html"><i class="fa fa-home"></i> Home</a>
        <!-- Divider -->
        <span class="divider">/</span>
        <a href="#" class="bread-current">FISL 15</a>
      </div>
      <div class="clearfix"></div>
    </div>
    <!-- Page heading ends -->
	
	<!-- Matter -->
	<div class="matter">
	  <div class="container">
	    <div class="row">
          {% block matter %}{% endblock %}
	    </div>
	  </div>
    </div>
	<!-- End Matter -->

  </div>
  <!-- Mainbar ends -->

  <div class="clearfix"></div>
</div>

{% endblock content %}
<!-- Content ends -->

<!-- Footer starts -->
<footer>
{% comment %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
            <!-- Copyright info -->
            <p class="copy">Copyright &copy; 2012 | <a href="#">Your Site</a> </p>
      </div>
    </div>
  </div>
{% endcomment %}
</footer> 	

<!-- Footer ends -->

<!-- Scroll to top -->
<span class="totop"><a href="#"><i class="fa fa-chevron-up"></i></a></span>

<!-- JS -->
<script src="{% static 'js/jquery.js' %}"></script> <!-- jQuery -->
<script src="{% static 'js/bootstrap.min.js' %}"></script> <!-- Bootstrap -->
<script src="{% static 'js/jquery-ui.min.js' %}"></script> <!-- jQuery UI -->
<script src="{% static 'js/fullcalendar.min.js' %}"></script> <!-- Full Google Calendar - Calendar -->
<script src="{% static 'js/jquery.rateit.min.js' %}"></script> <!-- RateIt - Star rating -->
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script> <!-- prettyPhoto -->
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script> <!-- jQuery Slim Scroll -->
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script> <!-- Data tables -->

<!-- jQuery Flot -->
<script src="{% static 'js/excanvas.min.js' %}"></script>
<script src="{% static 'js/jquery.flot.js' %}"></script>
<script src="{% static 'js/jquery.flot.resize.js' %}"></script>
<script src="{% static 'js/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/jquery.flot.stack.js' %}"></script>

<script src="{% static 'js/sparklines.js' %}"></script> <!-- Sparklines -->
<script src="{% static 'js/jquery.cleditor.min.js' %}"></script> <!-- CLEditor -->
<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script> <!-- Date picker -->
<script src="{% static 'js/jquery.onoff.min.js' %}"></script> <!-- Bootstrap Toggle -->
<script src="{% static 'js/filter.js' %}"></script> <!-- Filter for support page -->
<script src="{% static 'js/custom.js' %}"></script> <!-- Custom codes -->
<script src="{% static 'js/charts.js' %}"></script> <!-- Charts & Graphs -->

<script type="text/javascript">
{% block inline-js %}{% endblock %}
</script>

{% endblock %}
</body>
</html>

src/expenses/templates/dashboard.html
{% extends 'base.html' %}

{% block page-title %}
{{ block.super }} - Dashboard {% if attendee %} - <b>{{ attendee.first_name }}</b>{% endif %}
{% endblock %}

{% block inline-js %}
    $(function () {
        pie_chart_options = {
            series: {
                pie: {
                    show: true
                }
            },
            legend: {
                show: false
            }
        };

        {% if expense_by_category %}
            var category_data = [
            {% for expense in expense_by_category %}
                {'label': '{{ expense.category }}' , 'data': {{ expense.amount__sum }} },
            {% endfor %}
            ];
            $.plot($("#pie-chart-categories"), category_data, pie_chart_options);
        {% endif %}

        {% if not attendee and expense_by_attendee %}
            var attendee_data = [
            {% for expense in expense_by_attendee %}
                {'label': '{{ expense.attendee__first_name }}' ,
                 'data': {{ expense.amount__sum }} },
            {% endfor %}
            ];
            $.plot($("#pie-chart-attendees"), attendee_data, pie_chart_options);
        {% endif %}
    });
{% endblock %}

{% block matter %}

{% if expense_by_category %}
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left">Categories</div>
      <div class="clearfix"></div>
    </div>
    <div class="widget-content">
      <div class="padd">
        <div id="pie-chart-categories" class="pie-chart"></div>
      </div>
      <div class="widget-foot">
        <!-- Footer goes here -->
      </div>
    </div>
  </div>
</div>
{% endif %}

{% if not attendee and expense_by_attendee %}
<div class="col-md-6">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left">Attendees</div>
      <div class="clearfix"></div>
    </div>
    <div class="widget-content">
      <div class="padd">
        <div id="pie-chart-attendees" class="pie-chart"></div>
      </div>
      <div class="widget-foot">
        <!-- Footer goes here -->
      </div>
    </div>
  </div>
</div>
{% endif %}

<div class="col-md-12">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left">All Expenses</div>
      <div class="clearfix"></div>
    </div>
    <div class="widget-content">
      <div class="padd">
        {% include 'includes/table.html' %}
      </div>
      <div class="widget-foot">
        <!-- Footer goes here -->
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/expenses/templates/includes/table.html
<div class="page-tables">
  <div class="table-responsive">
    <table cellpadding="0" cellspacing="0" border="0" id="data-table" width="100%">
      <thead>
        <tr>
        {% for header in headers %}
          <th>{{ header }}</th>
        {% endfor %}
        </tr>
      </thead>

      <tbody>
        {% for row in data %}
        <tr>
          {% for field in row %}
            <td>{{ field|safe }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="clearfix"></div>
  </div>
</div>

src/expenses/templates/summary.html
{% extends 'base.html' %}

{% block page-title %}Summary{% endblock %}

{% block matter %}
<div class="col-md-12">
  <div class="widget">
    <div class="widget-head">
      <div class="pull-left">Summary</div>
      <div class="clearfix"></div>
    </div>
    <div class="widget-content">
      <div class="padd">
        {% include 'includes/table.html' %}
      </div>
      <div class="widget-foot">
        <!-- Footer goes here -->
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/expenses/templates/table.html
<div class="page-tables">
  <div class="table-responsive">
    <table cellpadding="0" cellspacing="0" border="0" id="data-table" width="100%">
      <thead>
        <tr>
        {% for header in headers %}
          <th>{{ header }}</th>
        {% endfor %}
        </tr>
      </thead>
    
      <tbody>
        {% for row in data %}
        <tr>
          {% for field in row %}
            <td>{{ field|safe|truncatechars:80 }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="clearfix"></div>
  </div>
</div>